{{- $top := . -}}
{{- range $store := .Values.clusterSecretStores }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ required "clusterSecretStores[].name is required" $store.name }}
  labels:
    {{- include "external-secrets-cr.labels" $top | nindent 4 }}
    {{- with $store.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $annot := include "external-secrets-cr.annotations" (dict "top" $top "extra" $store.annotations) }}
  {{- if $annot }}
  annotations:
    {{- $annot | nindent 4 }}
  {{- end }}
spec:
  provider:
    {{- toYaml (required "clusterSecretStores[].provider is required" $store.provider) | nindent 4 }}
  {{- with $store.refreshInterval }}
  refreshInterval: {{ . }}
  {{- end }}
  {{- with $store.retrySettings }}
  retrySettings:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $store.conditions }}
  conditions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $store.controller }}
  controller: {{ . }}
  {{- end }}
  {{- with $store.specExtra }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
{{- end }}
