{{- $top := . -}}
{{- range $ces := .Values.clusterExternalSecrets }}
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ required "clusterExternalSecrets[].name is required" $ces.name }}
  labels:
    {{- include "external-secrets-cr.labels" $top | nindent 4 }}
    {{- with $ces.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $annot := include "external-secrets-cr.annotations" (dict "top" $top "extra" $ces.annotations) }}
  {{- if $annot }}
  annotations:
    {{- $annot | nindent 4 }}
  {{- end }}
spec:
  {{- with $ces.externalSecretName }}
  externalSecretName: {{ . }}
  {{- end }}
  {{- with $ces.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $ces.namespaces }}
  namespaces:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $ces.namespaceSelectors }}
  namespaceSelectors:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $ces.refreshTime }}
  refreshTime: {{ . }}
  {{- end }}
  externalSecretSpec:
    {{- toYaml (required "clusterExternalSecrets[].externalSecretSpec is required" $ces.externalSecretSpec) | nindent 4 }}
  {{- with $ces.specExtra }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
{{- end }}
