{{- $top := . -}}
{{- range $es := .Values.externalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ required "externalSecrets[].name is required" $es.name }}
  namespace: {{ $es.namespace | default $top.Release.Namespace }}
  labels:
    {{- include "external-secrets-cr.labels" $top | nindent 4 }}
    {{- with $es.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $annot := include "external-secrets-cr.annotations" (dict "top" $top "extra" $es.annotations) }}
  {{- if $annot }}
  annotations:
    {{- $annot | nindent 4 }}
  {{- end }}
spec:
  {{- with $es.refreshInterval }}
  refreshInterval: {{ . }}
  {{- end }}
  {{- with $es.secretStoreRef }}
  secretStoreRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $es.target }}
  target:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $es.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $es.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $es.specExtra }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
{{- end }}
