{{- $top := . -}}
{{- range $ps := .Values.pushSecrets }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ required "pushSecrets[].name is required" $ps.name }}
  namespace: {{ $ps.namespace | default $top.Release.Namespace }}
  labels:
    {{- include "external-secrets-cr.labels" $top | nindent 4 }}
    {{- with $ps.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $annot := include "external-secrets-cr.annotations" (dict "top" $top "extra" $ps.annotations) }}
  {{- if $annot }}
  annotations:
    {{- $annot | nindent 4 }}
  {{- end }}
spec:
  {{- with $ps.refreshInterval }}
  refreshInterval: {{ . }}
  {{- end }}
  {{- with $ps.secretStoreRefs }}
  secretStoreRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $ps.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $ps.template }}
  template:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $ps.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $ps.updatePolicy }}
  updatePolicy: {{ . }}
  {{- end }}
  {{- with $ps.deletionPolicy }}
  deletionPolicy: {{ . }}
  {{- end }}
  {{- with $ps.specExtra }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
{{- end }}
