{{- $top := . -}}
{{- range $adv := .Values.bgpAdvertisements }}
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: {{ required "bgpAdvertisements[].name is required" $adv.name }}
  namespace: {{ $top.Release.Namespace }}
  labels:
    {{- include "metallb-cr.labels" $top | nindent 4 }}
    {{- with $adv.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $annot := include "metallb-cr.annotations" (dict "top" $top "extra" $adv.annotations) }}
  {{- if $annot }}
  annotations:
    {{- $annot | nindent 4 }}
  {{- end }}
spec:
  {{- if hasKey $adv "aggregationLength" }}
  aggregationLength: {{ $adv.aggregationLength }}
  {{- end }}
  {{- if hasKey $adv "aggregationLengthV6" }}
  aggregationLengthV6: {{ $adv.aggregationLengthV6 }}
  {{- end }}
  {{- if hasKey $adv "localPref" }}
  localPref: {{ $adv.localPref }}
  {{- end }}
  {{- with $adv.communities }}
  communities:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $adv.ipAddressPools }}
  ipAddressPools:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $adv.ipAddressPoolSelectors }}
  ipAddressPoolSelectors:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $adv.nodeSelectors }}
  nodeSelectors:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $adv.peers }}
  peers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $adv.specExtra }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
{{- end }}
