{{- $pm := .Values.podMonitor -}}
{{- if $pm.controller.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-nginx-gateway-controller
  namespace: {{ $pm.namespace }}
  labels:
    release: {{ $pm.releaseLabel }}
    {{- include "nginx-gateway-cr.labels" . | nindent 4 }}
    {{- with $pm.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    {{- if $pm.controller.namespaceSelector }}
    {{- toYaml $pm.controller.namespaceSelector | nindent 4 }}
    {{- else }}
    matchNames:
      - {{ .Release.Namespace }}
    {{- end }}
  selector:
    {{- toYaml $pm.controller.selector | nindent 4 }}
  podMetricsEndpoints:
    - port: {{ $pm.controller.port }}
      interval: {{ $pm.interval }}
      {{- with $pm.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      path: {{ $pm.controller.path }}
    {{- with $pm.controller.additionalEndpoints }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
