{{- if eq (include "buildkit.useConfigFile" .) "true" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "buildkit.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "buildkit.labels" . | nindent 4 }}
    app.kubernetes.io/component: buildkit
    {{- with .Values.resourceMetadata.configMap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $ann := include "buildkit.annotations" (dict "top" . "extra" .Values.resourceMetadata.configMap.annotations) }}
  {{- if $ann }}
  annotations:
    {{- $ann | nindent 4 }}
  {{- end }}
data:
  buildkitd.toml: |-
{{ include "buildkit.effectiveConfig" . | indent 4 }}
{{- end -}}
