{{- if and .Values.registry.caBundle.enabled (not .Values.registry.caBundle.existingSecret) -}}
{{- if not .Values.registry.caBundle.ca -}}
{{- fail "buildkit: registry.caBundle.ca is required when registry.caBundle.enabled is true and registry.caBundle.existingSecret is empty." -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buildkit.caSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "buildkit.labels" . | nindent 4 }}
    app.kubernetes.io/component: buildkit
    {{- with .Values.resourceMetadata.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $ann := include "buildkit.annotations" (dict "top" . "extra" .Values.resourceMetadata.secret.annotations) }}
  {{- if $ann }}
  annotations:
    {{- $ann | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.registry.caBundle.key }}: |-
{{ .Values.registry.caBundle.ca | indent 4 }}
{{- end }}
