{{- if and .Values.nginxGatewayFabric.proxySettings.enabled .Values.httproute.enabled -}}
apiVersion: gateway.nginx.org/v1alpha1
kind: ProxySettingsPolicy
metadata:
  name: {{ include "unity-mcp-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unity-mcp-server.labels" . | nindent 4 }}
    {{- with .Values.resourceMetadata.proxySettingsPolicy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $ann := include "unity-mcp-server.annotations" (dict "top" . "extra" .Values.resourceMetadata.proxySettingsPolicy.annotations) }}
  {{- if $ann }}
  annotations:
    {{- $ann | nindent 4 }}
  {{- end }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ include "unity-mcp-server.fullname" . }}
  buffering:
    disable: {{ .Values.nginxGatewayFabric.proxySettings.bufferingDisable }}
{{- end }}
