{{- $top := . -}}
{{- range $s := .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $s.name }}
  namespace: {{ $s.namespace }}
  labels:
    {{- include "certmanager-letsencrypt.labels" $top | nindent 4 }}
    {{- with $s.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $annot := include "certmanager-letsencrypt.annotations" (dict "top" $top "extra" $s.annotations) }}
  {{- if $annot }}
  annotations:
    {{- $annot | nindent 4 }}
  {{- end }}
type: {{ $s.type | default "Opaque" }}
{{- with $s.stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with $s.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
{{ end -}}
