{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kibana-eck.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kibana-eck.labels" . | nindent 4 }}
    {{- with .Values.resourceMetadata.networkPolicy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $ann := include "kibana-eck.annotations" (dict "top" . "extra" .Values.resourceMetadata.networkPolicy.annotations) }}
  {{- if $ann }}
  annotations:
    {{- $ann | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.networkPolicy.podSelector }}
  podSelector:
    {{- toYaml .Values.networkPolicy.podSelector | nindent 4 }}
  {{- else }}
  podSelector:
    matchLabels:
      common.k8s.elastic.co/type: kibana
      kibana.k8s.elastic.co/name: {{ include "kibana-eck.fullname" . }}
  {{- end }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
