{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kibana-eck.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kibana-eck.labels" . | nindent 4 }}
    {{- with .Values.resourceMetadata.podDisruptionBudget.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $ann := include "kibana-eck.annotations" (dict "top" . "extra" .Values.resourceMetadata.podDisruptionBudget.annotations) }}
  {{- if $ann }}
  annotations:
    {{- $ann | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      common.k8s.elastic.co/type: kibana
      kibana.k8s.elastic.co/name: {{ include "kibana-eck.fullname" . }}
{{- end }}
