{{- if .Values.elasticPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elasticsearch-eck.fullname" . }}-es-elastic-user
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticsearch-eck.labels" . | nindent 4 }}
    {{- with .Values.resourceMetadata.elasticUserSecret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $ann := include "elasticsearch-eck.annotations" (dict "top" . "extra" .Values.resourceMetadata.elasticUserSecret.annotations) }}
  {{- if $ann }}
  annotations:
    {{- $ann | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  elastic: {{ .Values.elasticPassword | quote }}
{{- end }}
