apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
    {{- with .Values.resourceMetadata.configMap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $ann := include "mysql.annotations" (dict "top" . "extra" .Values.resourceMetadata.configMap.annotations) }}
  {{- if $ann }}
  annotations:
    {{- $ann | nindent 4 }}
  {{- end }}
data:
  custom.cnf: |-
{{ .Values.customConfig | indent 4 }}
