{{- if not .Values.auth.existingSecret -}}
{{- if or (not .Values.auth.user) (not .Values.auth.password) (not .Values.auth.rootPassword) -}}
{{- fail "mysql: auth.{user,password,rootPassword} are all required when auth.existingSecret is empty." -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
    {{- with .Values.resourceMetadata.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $ann := include "mysql.annotations" (dict "top" . "extra" .Values.resourceMetadata.secret.annotations) }}
  {{- if $ann }}
  annotations:
    {{- $ann | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.auth.secretKeys.user }}: {{ .Values.auth.user | quote }}
  {{ .Values.auth.secretKeys.password }}: {{ .Values.auth.password | quote }}
  {{ .Values.auth.secretKeys.rootPassword }}: {{ .Values.auth.rootPassword | quote }}
{{- end }}
