{{- if .Values.httproute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "ghost.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
    {{- with .Values.resourceMetadata.httproute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $ann := include "ghost.annotations" (dict "top" . "extra" .Values.resourceMetadata.httproute.annotations) }}
  {{- if $ann }}
  annotations:
    {{- $ann | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httproute.parentRefs }}
  parentRefs:
    {{- range . }}
    - name: {{ .name }}
      {{- with .namespace }}
      namespace: {{ . }}
      {{- end }}
      {{- with .sectionName }}
      sectionName: {{ . }}
      {{- end }}
      {{- with .port }}
      port: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- with .Values.httproute.hostnames }}
  hostnames:
    {{- range . }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- $defaultSvc := include "ghost.fullname" . }}
    {{- $defaultPort := .Values.service.port }}
    {{- range .Values.httproute.rules }}
    - backendRefs:
        {{- range .backendRefs }}
        - name: {{ .name | default $defaultSvc }}
          port: {{ .port | default $defaultPort }}
          {{- with .weight }}
          weight: {{ . }}
          {{- end }}
        {{- end }}
      {{- with .matches }}
      matches:
        {{- range . }}
        - path:
            type: {{ .path.type | default "PathPrefix" }}
            value: {{ .path.value | default "/" | quote }}
          {{- with .headers }}
          headers:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .queryParams }}
          queryParams:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .method }}
          method: {{ . }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- with .filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .timeouts }}
      timeouts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
